### ISSUE TITLE
split-seq benchmark results

### ISSUE THREAD

**Issue by merckey** [JamesOpz/split_seq_zUMIs_pipeline#1]
Hi James,
Thank you for sharing the settings for the zUMIs pipeline!

Could you share a dataset you've been using for the development and the quantification results generated by the zUMIs pipeline?

We want to benchmark our pipeline to make sure we did things correctly. We have been testing with the data from Rosenberg et al. But couldn't find the corresponding results processed by zUMIs.

Greatly appreciate your help!
JL

**Comment by JamesOpz** [comment]
Hi JL,

Thanks for your interest in the SPLiT-seq zUMIs pipeline. I have initially been using one of the Figure 1 (Barnyard cell line mixing experiment) Rosenberg et al. datasets (GSE110823) to test the zUMIs pipeline, comparing the output to the corresponding processed .mtx data that is provided in the GEO repository associated with the paper.

With the settings provided in this repo you can run the zUMIs pipeline on whichever Rosenberg et al. FASTQ data you are using to benchmark your pipeline.

Best,
James
